apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: todo-react
  title: To-do in React
  description: A web-based To-do application, written in React. For demonstration purposes only!
  tags:
    - react
    - website
spec:
  type: service
  lifecycle: experimental
  owner: dev-support

---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: dev-support
  title: Development Support Team
  description: The development support team
spec:
  type: team
children: []
